# -*- coding: utf-8 -*-
__author__ = "NeveHanter <nevehanter@gmail.com>"

VCARD_VERSION_2_1 = '2.1'
VCARD_VERSION_3_0 = '3.0'
VCARD_VERSION_4_0 = '4.0'

TYPE_VCARD = 'vCard'
TYPE_XCARD = 'xCard'
TYPE_JCARD = 'jCard'
TYPE_HCARD = 'hCard'
TYPE_H_CARD = 'h-card'
TYPE_CSV = 'csv'

VCARD_MIMES_PRIOR_4_0 = ["text/vcard"]
VCARD_MIMES_4_0 = ["text/x-vcard", "text/directory;profile=vCard", "text/directory"]

VCARD_2_1_STANDARD_TAGS = ["ADR", "AGENT", "BDAY", "BEGIN", "CATEGORIES", "EMAIL", "END", "FN", "GEO", "KEY", "LABEL", "LOGO", "MAILER", "N", "NOTE", "ORG", "PHOTO", "PROFILE", "REV", "ROLE", "^SORT$-^STRING$", "SOUND", "SOURCE", "TEL", "TITLE", "TZ", "UID", "URL", "VERSION"]
VCARD_3_0_STANDARD_TAGS = ["ADR", "AGENT", "BDAY", "BEGIN", "CATEGORIES", "CLASS", "EMAIL", "END", "FN", "GEO", "IMPP", "KEY", "LABEL", "LOGO", "MAILER", "N", "NAME", "NICKNAME", "NOTE", "ORG", "PHOTO", "PRODID", "PROFILE", "REV", "ROLE", "^SORT$-^STRING$", "SOUND", "SOURCE", "TEL", "TITLE", "TZ", "UID", "URL", "VERSION"]
VCARD_4_0_STANDARD_TAGS = ["ADR", "ANNIVERSARY", "BDAY", "BEGIN", "CALADRURI", "CALURI", "CATEGORIES", "CLIENTPIDMAP", "EMAIL", "END", "FBURL", "FN", "GENDER", "GEO", "IMPP", "KEY", "KIND", "LANG", "LOGO", "N", "NICKNAME", "NOTE", "ORG", "PHOTO", "PRODID", "REV", "ROLE", "SOUND", "SOURCE", "TEL", "TITLE", "TZ", "UID", "URL", "VERSION", "XML"]

VCARD_X_TAG = '^X-([\w\d-]+)$'

VCARD_2_1_REQUIRED_TAGS = ["BEGIN", "END", "N", "VERSION"]
VCARD_3_0_REQUIRED_TAGS = ["BEGIN", "END", "FN", "N", "VERSION"]
VCARD_4_0_REQUIRED_TAGS = ["BEGIN", "END", "FN", "VERSION"]

VCARD_STANDARD_TAGS_MAP = {
    VCARD_VERSION_2_1: VCARD_2_1_STANDARD_TAGS,
    VCARD_VERSION_3_0: VCARD_3_0_STANDARD_TAGS,
    VCARD_VERSION_4_0: VCARD_4_0_STANDARD_TAGS
}

VCARD_REQUIRED_TAGS_MAP = {
    VCARD_VERSION_2_1: VCARD_2_1_REQUIRED_TAGS,
    VCARD_VERSION_3_0: VCARD_3_0_REQUIRED_TAGS,
    VCARD_VERSION_4_0: VCARD_4_0_REQUIRED_TAGS
}

CSV_MIMES = ["text/csv"]
CSV_DELIMITERS = [',', ';', '|', '\t', ' ']